### PR TITLE
Include preview in the readme

### PR DESCRIPTION
**Pull request by cetra3**
Simple change to include a preview in the readme so users can see what it looks like

### CODE REVIEW

**Comment by maghoff** [comment]
Hi! Thank you for this and sorry for not replying earlier.

I like the idea, but I'm kind of on the fence about this exact PR. I have two itches: First, the image is low-resolution. I'd like it very much if it looked sharp on a "retina" screen. Second, the image is very tall. As it is, I think it breaks up the flow of the surrounding text too much.

What do you think?

**Comment by cetra3** [comment]
Sure they're great suggestions.  I'm not sure how to generate a high res image as I'm just taking it straight from a web browser.

**Comment by maghoff** [comment]
Ok. Thanks for you input. I'll pick this up again when I'm doing a new publicity push.

**Comment by cetra3** [comment]
No worries!

**Pull request closed without merging**
